### ISSUE TITLE
Page Handling

### ISSUE THREAD

**Issue by Master-Daniel** [Cuadrix/puppeteer-page-proxy#103]
there is a recent update of puppeteer and when a new tab is created it no longer provides 

```
CDPPage {
  emitter: {
    all: Map(0) {},
    on: [Function: on],
    off: [Function: off],
    emit: [Function: emit]
  },
  eventsMap: Map(0) {}
}
```

this is what is been created once a new tab is created ```CdpPage { _isDragging: false }```

Hence I get the error below

```
useProxyPer[target.constructor.name](target, data);
                                        ^
TypeError: useProxyPer[target.constructor.name] is not a function
```

even when I tried to rename CDPPage to CdpPage  I still got another error from the removeRequestListener function located at node_modules\puppeteer-page-proxy\src\core\proxy.js

```
const listeners = page.eventsMap.get(eventName);
                                     ^
TypeError: Cannot read properties of undefined (reading 'get')
```

**Comment by oliveremberton** [comment]
Same here, seems to work with Puppeteer 21.2.x but not Puppeteer 21.3.x.

**Comment by LeM0-Dev** [comment]
Duplicate! Use code in this pull request. #101

**Comment by LeM0-Dev** [comment]
You can use https://www.npmjs.com/package/@lem0-packages/puppeteer-page-proxy
if you want

**Comment by harisrozak** [comment]
> You can use https://www.npmjs.com/package/@lem0-packages/puppeteer-page-proxy if you want

I have tried your package, but still getting this error:
"Cannot read properties of undefined (reading 'get')"

**Comment by LeM0-Dev** [comment]
> > You can use https://www.npmjs.com/package/@lem0-packages/puppeteer-page-proxy if you want
> 
> I have tried your package, but still getting this error: "Cannot read properties of undefined (reading 'get')"

Because you are using dappeteer.
https://github.com/LeM0-Dev/puppeteer-page-proxy/issues/2#issuecomment-1826760916

**Comment by GinoGreen** [comment]
> > > You can use https://www.npmjs.com/package/@lem0-packages/puppeteer-page-proxy if you want
> > 
> > 
> > I have tried your package, but still getting this error: "Cannot read properties of undefined (reading 'get')"
> 
> Because you are using dappeteer. [LeM0-Dev#2 (comment)](https://github.com/LeM0-Dev/puppeteer-page-proxy/issues/2#issuecomment-1826760916)


I'm your proxy repo with puppeteer-cluster, and i'm getting the same error: Cannot read properties of undefined (reading 'get')

Is there a problem using puppeteer-cluster?

**Comment by ofirsnb** [comment]
> You can use https://www.npmjs.com/package/@lem0-packages/puppeteer-page-proxy if you want

Can confirm this is working great with latest `puppeteer` version `21.9.0`.

Thank you LeM0-Dev !
